### ISSUE TITLE
update the docker to support latest bigdl and intel analytics zoo versions

### ISSUE THREAD

**Issue by sujee** [elephantscale/bigdl-docker#1]

**Comment by mehrlog** [comment]
`MAINTAINER` has been deprecated so I changed it to `LABEL maintainer`.

I update `BIGDL 0.6.0 -> 0.8.0` , `ANALYTICS_ZOO 0.3.0 -> 0.5.0` , `SPARK 2.3.1 -> 2.4.0`

Also version 0.9.0 is available for BIGDL, 2.4.1 is available for SPARK and 2.12 is available for SCALA.
they are exist in [archive.apache.org](https://archive.apache.org/dist/spark) but not exist in [repo1.maven.org](https://repo1.maven.org/maven2/com/intel/analytics/bigdl/) so I used 0.8.0 , 2.4.0 and 2.11.8 for bigdl, SPARK and SCALA
